# Generated by Django 3.2.7 on 2021-10-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='After',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.EmailField(max_length=30)),
                ('receiver', models.EmailField(max_length=30)),
                ('amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('email_id', models.EmailField(max_length=300, unique=True)),
                ('mobile_no', models.IntegerField()),
                ('bank_id', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=3000)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
